name: Smoke Test - .NET on Functions V2

on:
  {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run V2 .NET Smoke Test
      run: test/SmokeTests/e2e-test.ps1 -DockerfilePath test/SmokeTests/SmokeTestsV2/Dockerfile -HttpStartPath api/HttpStart
      shell: pwsh
